# Generated by Django 4.2.5 on 2024-02-24 22:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Herramienta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_mantenimiento', models.CharField(choices=[('PM', 'Preventivo'), ('GR', 'Garantía'), ('CM', 'Correctivo'), ('OV', 'Overhaul')], max_length=10)),
                ('nombre', models.CharField(blank=True, max_length=200)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('fabricante', models.CharField(blank=True, max_length=200)),
                ('parte_numero', models.CharField(blank=True, max_length=200)),
                ('serie_numero', models.CharField(blank=True, max_length=200)),
                ('inspeccion_de_recibo', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'herramienta',
                'verbose_name_plural': 'herramientas',
            },
        ),
        migrations.CreateModel(
            name='OrdenDeTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=200)),
                ('consecutivo', models.CharField(blank=True, max_length=200)),
                ('estado', models.CharField(choices=[('AB', 'Abierta'), ('CR', 'Cerrada')], max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierre', models.DateTimeField(auto_now_add=True)),
                ('lugar', models.CharField(blank=True, max_length=200)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('herramienta', models.ManyToManyField(to='mantenimiento.herramienta')),
            ],
            options={
                'verbose_name': 'orden de trabajo',
                'verbose_name_plural': 'ordenes de trabajo',
            },
        ),
    ]
