# Generated by Django 4.2.5 on 2024-02-24 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herramienta',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='herramienta',
            name='fabricante',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='herramienta',
            name='inspeccion_de_recibo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='herramienta',
            name='nombre',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='herramienta',
            name='parte_numero',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='herramienta',
            name='serie_numero',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ordendetrabajo',
            name='consecutivo',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ordendetrabajo',
            name='fecha_cierre',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordendetrabajo',
            name='herramienta',
            field=models.ManyToManyField(blank=True, null=True, to='mantenimiento.herramienta'),
        ),
        migrations.AlterField(
            model_name='ordendetrabajo',
            name='lugar',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ordendetrabajo',
            name='nombre',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
