# Generated by Django 4.2.5 on 2024-02-24 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0002_alter_herramienta_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herramienta',
            name='tipo_mantenimiento',
            field=models.CharField(choices=[('PM', 'Preventivo'), ('CM', 'Correctivo'), ('OV', 'Overhaul'), ('GR', 'Garantía')], max_length=10),
        ),
    ]
