# Generated by Django 4.2.5 on 2024-02-19 05:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeMaintenance', models.CharField(choices=[('PM', 'Preventivo'), ('CM', 'Correctivo'), ('OV', 'Overhaull')], max_length=10)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('brand', models.CharField(blank=True, max_length=200)),
                ('model', models.CharField(blank=True, max_length=200)),
                ('usernumber', models.CharField(blank=True, max_length=200)),
                ('receiptInspection', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'tool',
                'verbose_name_plural': 'tools',
            },
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('consecutive', models.CharField(blank=True, max_length=200)),
                ('state', models.CharField(choices=[('RC', 'Recibido'), ('MTO', 'En Mantenimiento'), ('EN', 'Entregado')], max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('endDate', models.DateTimeField(auto_now_add=True)),
                ('place', models.CharField(blank=True, max_length=200)),
                ('tools', models.ManyToManyField(to='maintenance_management.tools')),
                ('userApplicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'work_order',
                'verbose_name_plural': 'work_orders',
            },
        ),
    ]
