# Generated by Django 4.2.5 on 2024-02-20 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tools',
            name='typeMaintenance',
            field=models.CharField(choices=[('PM', 'Preventivo'), ('CM', 'Correctivo'), ('OV', 'Overhaul')], max_length=10),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='state',
            field=models.CharField(choices=[('AB', 'Abierta'), ('CR', 'Cerrada')], max_length=10),
        ),
    ]
